package com.book.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BorrowInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public BorrowInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReaderIdIsNull() {
            addCriterion("reader_id is null");
            return (Criteria) this;
        }

        public Criteria andReaderIdIsNotNull() {
            addCriterion("reader_id is not null");
            return (Criteria) this;
        }

        public Criteria andReaderIdEqualTo(Integer value) {
            addCriterion("reader_id =", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotEqualTo(Integer value) {
            addCriterion("reader_id <>", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdGreaterThan(Integer value) {
            addCriterion("reader_id >", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("reader_id >=", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdLessThan(Integer value) {
            addCriterion("reader_id <", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdLessThanOrEqualTo(Integer value) {
            addCriterion("reader_id <=", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdIn(List<Integer> values) {
            addCriterion("reader_id in", values, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotIn(List<Integer> values) {
            addCriterion("reader_id not in", values, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdBetween(Integer value1, Integer value2) {
            addCriterion("reader_id between", value1, value2, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("reader_id not between", value1, value2, "readerId");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNull() {
            addCriterion("book_isbn is null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNotNull() {
            addCriterion("book_isbn is not null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnEqualTo(String value) {
            addCriterion("book_isbn =", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotEqualTo(String value) {
            addCriterion("book_isbn <>", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThan(String value) {
            addCriterion("book_isbn >", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("book_isbn >=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThan(String value) {
            addCriterion("book_isbn <", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThanOrEqualTo(String value) {
            addCriterion("book_isbn <=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLike(String value) {
            addCriterion("book_isbn like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotLike(String value) {
            addCriterion("book_isbn not like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIn(List<String> values) {
            addCriterion("book_isbn in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotIn(List<String> values) {
            addCriterion("book_isbn not in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnBetween(String value1, String value2) {
            addCriterion("book_isbn between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotBetween(String value1, String value2) {
            addCriterion("book_isbn not between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIsNull() {
            addCriterion("book_borrow_time is null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIsNotNull() {
            addCriterion("book_borrow_time is not null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeEqualTo(Date value) {
            addCriterion("book_borrow_time =", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotEqualTo(Date value) {
            addCriterion("book_borrow_time <>", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeGreaterThan(Date value) {
            addCriterion("book_borrow_time >", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("book_borrow_time >=", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeLessThan(Date value) {
            addCriterion("book_borrow_time <", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeLessThanOrEqualTo(Date value) {
            addCriterion("book_borrow_time <=", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIn(List<Date> values) {
            addCriterion("book_borrow_time in", values, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotIn(List<Date> values) {
            addCriterion("book_borrow_time not in", values, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeBetween(Date value1, Date value2) {
            addCriterion("book_borrow_time between", value1, value2, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotBetween(Date value1, Date value2) {
            addCriterion("book_borrow_time not between", value1, value2, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeIsNull() {
            addCriterion("book_return_time is null");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeIsNotNull() {
            addCriterion("book_return_time is not null");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeEqualTo(Date value) {
            addCriterion("book_return_time =", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeNotEqualTo(Date value) {
            addCriterion("book_return_time <>", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeGreaterThan(Date value) {
            addCriterion("book_return_time >", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("book_return_time >=", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeLessThan(Date value) {
            addCriterion("book_return_time <", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeLessThanOrEqualTo(Date value) {
            addCriterion("book_return_time <=", value, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeIn(List<Date> values) {
            addCriterion("book_return_time in", values, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeNotIn(List<Date> values) {
            addCriterion("book_return_time not in", values, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeBetween(Date value1, Date value2) {
            addCriterion("book_return_time between", value1, value2, "bookReturnTime");
            return (Criteria) this;
        }

        public Criteria andBookReturnTimeNotBetween(Date value1, Date value2) {
            addCriterion("book_return_time not between", value1, value2, "bookReturnTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 09 13:15:17 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}