package com.book.pojo;

import java.util.Date;

public class BorrowInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private Integer readerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_info.book_isbn
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private String bookIsbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_info.book_borrow_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private Date bookBorrowTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_info.book_return_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private Date bookReturnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_info.reader_id
     *
     * @return the value of borrow_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Integer getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_info.reader_id
     *
     * @param readerId the value for borrow_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_info.book_isbn
     *
     * @return the value of borrow_info.book_isbn
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_info.book_isbn
     *
     * @param bookIsbn the value for borrow_info.book_isbn
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_info.book_borrow_time
     *
     * @return the value of borrow_info.book_borrow_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Date getBookBorrowTime() {
        return bookBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_info.book_borrow_time
     *
     * @param bookBorrowTime the value for borrow_info.book_borrow_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setBookBorrowTime(Date bookBorrowTime) {
        this.bookBorrowTime = bookBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_info.book_return_time
     *
     * @return the value of borrow_info.book_return_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Date getBookReturnTime() {
        return bookReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_info.book_return_time
     *
     * @param bookReturnTime the value for borrow_info.book_return_time
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setBookReturnTime(Date bookReturnTime) {
        this.bookReturnTime = bookReturnTime;
    }
}