package com.book.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReaderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public ReaderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReaderIdIsNull() {
            addCriterion("reader_id is null");
            return (Criteria) this;
        }

        public Criteria andReaderIdIsNotNull() {
            addCriterion("reader_id is not null");
            return (Criteria) this;
        }

        public Criteria andReaderIdEqualTo(Integer value) {
            addCriterion("reader_id =", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotEqualTo(Integer value) {
            addCriterion("reader_id <>", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdGreaterThan(Integer value) {
            addCriterion("reader_id >", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("reader_id >=", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdLessThan(Integer value) {
            addCriterion("reader_id <", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdLessThanOrEqualTo(Integer value) {
            addCriterion("reader_id <=", value, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdIn(List<Integer> values) {
            addCriterion("reader_id in", values, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotIn(List<Integer> values) {
            addCriterion("reader_id not in", values, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdBetween(Integer value1, Integer value2) {
            addCriterion("reader_id between", value1, value2, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("reader_id not between", value1, value2, "readerId");
            return (Criteria) this;
        }

        public Criteria andReaderGenderIsNull() {
            addCriterion("reader_gender is null");
            return (Criteria) this;
        }

        public Criteria andReaderGenderIsNotNull() {
            addCriterion("reader_gender is not null");
            return (Criteria) this;
        }

        public Criteria andReaderGenderEqualTo(String value) {
            addCriterion("reader_gender =", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderNotEqualTo(String value) {
            addCriterion("reader_gender <>", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderGreaterThan(String value) {
            addCriterion("reader_gender >", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderGreaterThanOrEqualTo(String value) {
            addCriterion("reader_gender >=", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderLessThan(String value) {
            addCriterion("reader_gender <", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderLessThanOrEqualTo(String value) {
            addCriterion("reader_gender <=", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderLike(String value) {
            addCriterion("reader_gender like", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderNotLike(String value) {
            addCriterion("reader_gender not like", value, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderIn(List<String> values) {
            addCriterion("reader_gender in", values, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderNotIn(List<String> values) {
            addCriterion("reader_gender not in", values, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderBetween(String value1, String value2) {
            addCriterion("reader_gender between", value1, value2, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderGenderNotBetween(String value1, String value2) {
            addCriterion("reader_gender not between", value1, value2, "readerGender");
            return (Criteria) this;
        }

        public Criteria andReaderBirthIsNull() {
            addCriterion("reader_birth is null");
            return (Criteria) this;
        }

        public Criteria andReaderBirthIsNotNull() {
            addCriterion("reader_birth is not null");
            return (Criteria) this;
        }

        public Criteria andReaderBirthEqualTo(Date value) {
            addCriterion("reader_birth =", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthNotEqualTo(Date value) {
            addCriterion("reader_birth <>", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthGreaterThan(Date value) {
            addCriterion("reader_birth >", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthGreaterThanOrEqualTo(Date value) {
            addCriterion("reader_birth >=", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthLessThan(Date value) {
            addCriterion("reader_birth <", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthLessThanOrEqualTo(Date value) {
            addCriterion("reader_birth <=", value, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthIn(List<Date> values) {
            addCriterion("reader_birth in", values, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthNotIn(List<Date> values) {
            addCriterion("reader_birth not in", values, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthBetween(Date value1, Date value2) {
            addCriterion("reader_birth between", value1, value2, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderBirthNotBetween(Date value1, Date value2) {
            addCriterion("reader_birth not between", value1, value2, "readerBirth");
            return (Criteria) this;
        }

        public Criteria andReaderAdressIsNull() {
            addCriterion("reader_adress is null");
            return (Criteria) this;
        }

        public Criteria andReaderAdressIsNotNull() {
            addCriterion("reader_adress is not null");
            return (Criteria) this;
        }

        public Criteria andReaderAdressEqualTo(String value) {
            addCriterion("reader_adress =", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressNotEqualTo(String value) {
            addCriterion("reader_adress <>", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressGreaterThan(String value) {
            addCriterion("reader_adress >", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressGreaterThanOrEqualTo(String value) {
            addCriterion("reader_adress >=", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressLessThan(String value) {
            addCriterion("reader_adress <", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressLessThanOrEqualTo(String value) {
            addCriterion("reader_adress <=", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressLike(String value) {
            addCriterion("reader_adress like", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressNotLike(String value) {
            addCriterion("reader_adress not like", value, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressIn(List<String> values) {
            addCriterion("reader_adress in", values, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressNotIn(List<String> values) {
            addCriterion("reader_adress not in", values, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressBetween(String value1, String value2) {
            addCriterion("reader_adress between", value1, value2, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderAdressNotBetween(String value1, String value2) {
            addCriterion("reader_adress not between", value1, value2, "readerAdress");
            return (Criteria) this;
        }

        public Criteria andReaderTelIsNull() {
            addCriterion("reader_tel is null");
            return (Criteria) this;
        }

        public Criteria andReaderTelIsNotNull() {
            addCriterion("reader_tel is not null");
            return (Criteria) this;
        }

        public Criteria andReaderTelEqualTo(String value) {
            addCriterion("reader_tel =", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelNotEqualTo(String value) {
            addCriterion("reader_tel <>", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelGreaterThan(String value) {
            addCriterion("reader_tel >", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelGreaterThanOrEqualTo(String value) {
            addCriterion("reader_tel >=", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelLessThan(String value) {
            addCriterion("reader_tel <", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelLessThanOrEqualTo(String value) {
            addCriterion("reader_tel <=", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelLike(String value) {
            addCriterion("reader_tel like", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelNotLike(String value) {
            addCriterion("reader_tel not like", value, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelIn(List<String> values) {
            addCriterion("reader_tel in", values, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelNotIn(List<String> values) {
            addCriterion("reader_tel not in", values, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelBetween(String value1, String value2) {
            addCriterion("reader_tel between", value1, value2, "readerTel");
            return (Criteria) this;
        }

        public Criteria andReaderTelNotBetween(String value1, String value2) {
            addCriterion("reader_tel not between", value1, value2, "readerTel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 09 13:15:17 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reader_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}