package com.book.pojo;

import java.util.Date;

public class Reader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private Integer readerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_gender
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private String readerGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_birth
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private Date readerBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_adress
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private String readerAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader_info.reader_tel
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    private String readerTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_id
     *
     * @return the value of reader_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Integer getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_id
     *
     * @param readerId the value for reader_info.reader_id
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_gender
     *
     * @return the value of reader_info.reader_gender
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getReaderGender() {
        return readerGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_gender
     *
     * @param readerGender the value for reader_info.reader_gender
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderGender(String readerGender) {
        this.readerGender = readerGender == null ? null : readerGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_birth
     *
     * @return the value of reader_info.reader_birth
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public Date getReaderBirth() {
        return readerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_birth
     *
     * @param readerBirth the value for reader_info.reader_birth
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderBirth(Date readerBirth) {
        this.readerBirth = readerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_adress
     *
     * @return the value of reader_info.reader_adress
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getReaderAdress() {
        return readerAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_adress
     *
     * @param readerAdress the value for reader_info.reader_adress
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderAdress(String readerAdress) {
        this.readerAdress = readerAdress == null ? null : readerAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader_info.reader_tel
     *
     * @return the value of reader_info.reader_tel
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public String getReaderTel() {
        return readerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader_info.reader_tel
     *
     * @param readerTel the value for reader_info.reader_tel
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    public void setReaderTel(String readerTel) {
        this.readerTel = readerTel == null ? null : readerTel.trim();
    }
}