package com.book.dao;

import com.book.pojo.AdminAccount;
import com.book.pojo.AdminAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    long countByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int deleteByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int deleteByPrimaryKey(String adminName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int insert(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int insertSelective(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    List<AdminAccount> selectByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    AdminAccount selectByPrimaryKey(String adminName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminAccount record, @Param("example") AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByExample(@Param("record") AdminAccount record, @Param("example") AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByPrimaryKeySelective(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByPrimaryKey(AdminAccount record);
}