package com.book.dao;

import com.book.pojo.BorrowInfo;
import com.book.pojo.BorrowInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    long countByExample(BorrowInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int deleteByExample(BorrowInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int insert(BorrowInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int insertSelective(BorrowInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    List<BorrowInfo> selectByExample(BorrowInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") BorrowInfo record, @Param("example") BorrowInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_info
     *
     * @mbg.generated Sat Mar 09 13:15:17 CST 2019
     */
    int updateByExample(@Param("record") BorrowInfo record, @Param("example") BorrowInfoExample example);
}